output "vpc_id"               { value = aws_vpc.this.id }
output "vpc_cidr_block"       { value = aws_vpc.this.cidr_block }
output "public_subnet_ids"    { value = aws_subnet.public[*].id }
output "private_subnet_ids"   { value = aws_subnet.private[*].id }
output "internet_gateway_id"  { value = aws_internet_gateway.this.id }
output "nat_gateway_id"       { value = var.enable_nat_gateway ? aws_nat_gateway.this[0].id : null }
output "nat_eip"              { value = var.enable_nat_gateway ? aws_eip.nat[0].public_ip : null }
output "public_route_table_id"  { value = aws_route_table.public.id }
output "private_route_table_id" { value = aws_route_table.private.id }
output "availability_zones"   { value = var.availability_zones }
